export const DOCUMENT_FIELDS=['passportName','passportNumber','nationality','passportDob','passportExpiry','visaName','visaNumber','visaDob','visaType','visaExpiry'];
const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
export function dateValue(s){let m=String(s).toUpperCase().match(/\b(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})\b/),parts;if(m)parts=[+m[1],+m[2],+m[3]];else if(m=String(s).toUpperCase().match(/\b(\d{1,2})[\s/.-]+([A-Z]{3})[A-Z]*[\s/.-]+(\d{4})\b/))parts=[+m[3],months.indexOf(m[2])+1,+m[1]];else if(m=String(s).match(/\b(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})\b/))parts=[+m[3],+m[2],+m[1]];if(!parts)return '';const [y,mo,d]=parts;if(y<1900||y>2200||mo<1||mo>12||d<1||d>31)return '';const v=y+'-'+String(mo).padStart(2,'0')+'-'+String(d).padStart(2,'0');return new Date(v).toISOString().slice(0,10)===v?v:'';}
const nameValue=s=>{const m=s.replace(/^[^A-Za-z]+/,'').match(/^[A-Za-z][A-Za-z '\-]{2,90}/);if(!m)return '';const v=m[0].trim();if(!/^[A-Z]/.test(v))return '';return /passport|national|birth|expiry|country|surname|given name|place of|date of|sex|specimen/i.test(v)?'':v;};
export function parseDocument(raw,confidence=0){const text=String(raw||'').slice(0,24000),lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const documentType=/\bVISA\b/i.test(text)?'visa':/\b(PASSPORT|PASSEPORT|PASAPORTE)\b/i.test(text)?'passport':'unknown';const fields={},evidence={};
function search(label,convert){for(let i=0;i<lines.length;i++){const m=lines[i].match(label);if(!m)continue;const tail=lines[i].slice(m.index+m[0].length).replace(/^\s*[:./-]+\s*/,'');for(const [j,s] of [[i,tail],[i+1,lines[i+1]||''],[i+2,lines[i+2]||'']]){const v=convert(s);if(v)return {value:v,line:lines[j]};}}return null;}
function set(k,found){if(found){fields[k]=found.value;evidence[k]=found.line;}}
if(documentType!=='unknown'){const prefix=documentType;set(prefix+'Name',search(/\b(?:full\s*names?|names?|name\s*of\s*holder)\b/i,nameValue));if(!fields[prefix+'Name']){const sur=search(/\bSurname\b/i,nameValue),given=search(/\bGiven\s*names?\b/i,nameValue);if(sur&&given)set(prefix+'Name',{value:given.value+' '+sur.value,line:given.line+' / '+sur.line});}
set(prefix+'Dob',search(/\b(?:date\s*of\s*birth|birth\s*date|D\.?O\.?B\.?)\b/i,dateValue));set(prefix+'Expiry',search(/\b(?:(?:date\s*)?of\s*expiry|expiry(?:\s*date)?|expiration(?:\s*date)?|valid\s*until)\b/i,dateValue));
set(prefix+'Number',search(new RegExp('\\b'+prefix+'\\s*(?:no\\.?|number)\\b','i'),s=>s.toUpperCase().match(/\b(?=[A-Z0-9]{6,14}\b)(?=[A-Z0-9]*\d)[A-Z0-9]+\b/)?.[0]||''));
if(prefix==='passport')set('nationality',search(/\bNationalit(?:y|i)\b/i,s=>nameValue(s)));else set('visaType',search(/\bvisa\s*type\b/i,s=>s.match(/^[A-Za-z][A-Za-z -]{2,35}/)?.[0]?.trim()||''));}
const complete=documentType!=='unknown'&&!!fields[documentType+'Name']&&!!fields[documentType+'Dob'];const warnings=[];if(!complete)warnings.push('Some basic fields could not be read. Retake the document or enter missing values.');if(Number(confidence)<70)warnings.push('Low OCR confidence. Compare extracted values with the original.');if(/\b\d{1,2}[/.-]\d{1,2}[/.-]\d{4}\b/.test(text))warnings.push('Numeric dates are interpreted as day/month/year; confirm the document convention.');return {documentType,fields,evidence,text,confidence:Math.max(0,Math.min(100,Number(confidence)||0)),status:complete?'extracted':'partial',warnings,engine:'Tesseract.js 7 / English',verified:false};}
export function mergeOcrFields(previous,result,capture){const data={...previous,_ocr:{...previous._ocr}};const type=capture.document_type;for(const key of DOCUMENT_FIELDS)if(key.startsWith(type)||(type==='passport'&&key==='nationality'))delete data[key];if(['passport','visa'].includes(type)&&result.documentType===type)Object.assign(data,result.fields);data._ocr[type]={...result,captureId:capture.id,reviewed:false};return data;}
export function editFields(previous,values){const data={_ocr:{...previous._ocr}};for(const key of DOCUMENT_FIELDS)data[key]=String(values[key]??'').trim().slice(0,150);for(const [type,record] of Object.entries(data._ocr)){const changed=DOCUMENT_FIELDS.some(k=>(k.startsWith(type)||(type==='passport'&&k==='nationality'))&&(data[k]||'')!==(previous[k]||''));if(changed)data._ocr[type]={...record,manuallyEdited:true};}return data;}
